server:
  port: 
spring:
  datasource:
  #本地数据库
#    url: jdbc:mysql://localhost:3306/littlee?useSSL=false
#    username:
#    password: 
  #服务器数据库
    url: jdbc:mysql://:3306/littlee?useSSL=false
    username: 
    password: 
    
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
#    schema:
#    - classpath:employee.sql
mybatis:
  config-location: classpath:Mybatis/Mybatis-config.xml
#  mapper-locations:
#  - classpath:Mybatis/Mapper/*.xml